name = "tidesync"
compatibility_date = "2025-04-20"

# point Wrangler at your built JS entrypoint
main = "workers-site/index.js"

[build]
# only build—not export
command = "npm run build"

[site]
bucket = "./out"

