# wrangler.toml
name = "tidesync"                     
compatibility_date = "2025-04-20"     

# Wrangler v4 expects your static site’s Worker script here
main = "workers-site/worker.js"

[site]
  bucket = "./out"                   