# wrangler.toml
name = "tidesync"                     
compatibility_date = "2025-04-20"      
type = "javascript"                    

# Wrangler v4 will generate a “workers-site/index.js” entry for you
main = "workers-site/index.js"

[site]
  bucket = "./out"                     
