name = "tidesync"                       
compatibility_date = "2025-04-20"    

# If you have an account_id, uncomment and fill it in:
# account_id = "your-cloudflare-account-id"

[site]
  bucket = "./out"
  entry-point = "workers-site"